# Generated by Django 3.2.12 on 2022-04-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0007_add_accesslog_trusted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='trusted',
        ),
    ]
